name: API & UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Configure these in GitHub Secrets; never commit real values to the repo
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_KEY: ${{ secrets.SECURITY_API_KEY }}
      UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
      UI_USERNAME: ${{ secrets.UI_USERNAME }}
      UI_PASSWORD: ${{ secrets.UI_PASSWORD }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
      ELASTICSEARCH_API_KEY: ${{ secrets.ELASTICSEARCH_API_KEY }}
      LOG_LEVEL: INFO
      ENVIRONMENT: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          pytest testsuites/api_testing/tests -q --maxfail=1

      - name: Run UI smoke (headless)
        run: |
          pytest testsuites/ui_testing/tests -q --maxfail=1
        env:
          HEADLESS: "true"

      # Optional: generate and upload Allure report
      # - name: Generate Allure report
      #   run: |
      #     allure generate reports/allure-results -o reports/allure-report --clean
      #   if: success() || failure()
      #
      # - name: Upload Allure report artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-report
      #     path: reports/allure-report

